name: "TorchInductor CUTLASS UTs"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  run-cutlass-test:
    name: Run TorchInductor CUTLASS test
    runs-on: bmg
    timeout-minutes: 120
  
    steps:
      - name: Checkout sycl-tla repo
        uses: actions/checkout@v4

      - name: Install Python venv package
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv

      - name: Install Intel graphics drivers
        uses: ./.github/actions/install-intel-graphics
        with:
          GPU: 'BMG'
          IGC: 'ROLLING'

      - name: Install DPC++
        id: install_dpcpp
        uses: ./.github/actions/install-dpcpp
        with:
          DPCPP_RELEASE: RELEASE
          DPCPP_PATH: ~/dpcpp

      - name: Setup virtual environment
        shell: bash
        run: |
          python3 -m venv ~/.pytorch-venv
          source ~/.pytorch-venv/bin/activate
          . setvars.sh
          env >> $GITHUB_ENV

      - name: Install nightly PyTorch
        shell: bash
        run: |
          source ~/.pytorch-venv/bin/activate
          python3 --version
          python3 -m pip install --pre torch==2.13.0.dev20260421+xpu --index-url https://download.pytorch.org/whl/nightly/xpu --force-reinstall

      - name: Print IGC2 version
        shell: bash
        run: |
          dpkg-query --show libigc2

      - name: Print PyTorch package version
        shell: bash
        run: |
          source ~/.pytorch-venv/bin/activate
          python3 -m pip list | grep -i torch

      - name: Clone PyTorch fork and install requirements
        shell: bash
        run: |
          source ~/.pytorch-venv/bin/activate
          cd ${{ runner.temp }}
          git clone https://github.com/pytorch/pytorch.git
          cd pytorch
          git checkout 03ca313c8043443b3efab2e21e7a9a09489fe974
          python3 -m pip install -r requirements.txt
          python3 -m pip install unittest-xml-reporting

      - name: Check Device compatibility
        shell: bash
        run: |
          source ~/.pytorch-venv/bin/activate
          export USE_XPU=1
          export CUTLASS_USE_SYCL=1
          export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
          export TORCH_XPU_ARCH_LIST=bmg
          export TORCHINDUCTOR_CUTLASS_DIR="${GITHUB_WORKSPACE}"
          python -c "import torch; print(torch.__version__)"
          python -c "import torch; print(torch.xpu.get_device_capability()['device_id'])"

      - name: Run TorchInductor EVT test
        shell: bash
        run: |
          source ~/.pytorch-venv/bin/activate
          export USE_XPU=1
          export CUTLASS_USE_SYCL=1
          export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
          export TORCH_XPU_ARCH_LIST=bmg
          export TORCHINDUCTOR_CUTLASS_DIR="${GITHUB_WORKSPACE}"
          mkdir -p ${GITHUB_WORKSPACE}/logs/
          cd ${{ runner.temp }}/pytorch
          python3 test/inductor/test_cutlass_evt.py -v 2>&1 | tee ${GITHUB_WORKSPACE}/logs/cutlass_inductor_evt.log

      - name: Run TorchInductor EVT test
        shell: bash
        run: |
          source ~/.pytorch-venv/bin/activate
          export USE_XPU=1
          export CUTLASS_USE_SYCL=1
          export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
          export TORCH_XPU_ARCH_LIST=bmg
          export TORCHINDUCTOR_CUTLASS_DIR="${GITHUB_WORKSPACE}"
          mkdir -p ${GITHUB_WORKSPACE}/logs/
          cd ${{ runner.temp }}/pytorch
          python3 test/inductor/test_cutlass_backend.py -v  2>&1 | tee ${GITHUB_WORKSPACE}/logs/cutlass_inductor_backend.log

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-artifacts
          path: logs/

      - name: Cleanup PyTorch repo and wheel
        if: always()
        shell: bash
        run: |
          rm -rf ${{ runner.temp }}/pytorch


